# Generated by Django 4.1.9 on 2023-06-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extract',
            name='name',
        ),
        migrations.AddField(
            model_name='extract',
            name='file',
            field=models.ImageField(blank=True, upload_to='my_picture'),
        ),
    ]
