# Generated by Django 4.1.9 on 2023-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extract', '0002_remove_extract_name_extract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='file',
            field=models.FileField(blank=True, upload_to='my_file'),
        ),
    ]
