# Generated by Django 4.1.9 on 2023-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extract', '0003_alter_extract_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extract',
            name='file',
        ),
        migrations.AddField(
            model_name='extract',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
