# Generated by Django 4.1.9 on 2023-06-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extract', '0005_rename_name_extract_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extract',
            name='detail',
        ),
    ]
